### Handling Inbalance datasets:-

1. Up sampling 
2. Down sampling

In [1]:
print("hello")

hello

In [2]:
import numpy as np 
import pandas as pd

#set the random seed for reproducibility
np.random.seed(123)

#create a dataframe with two classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [5]:
class_0 =pd.DataFrame({
        'feature_1':np.random.normal(loc=0, scale=1,size=n_class_0),
        'feature_2':np.random.normal(loc=0, scale=1, size=n_class_0),
        'target':[0]*n_class_0
        })

class_1 =pd.DataFrame({
    'feature_1':np.random.normal(loc=2, scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [7]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [9]:
df.head()

   feature_1  feature_2  target
0  -0.300232   0.667532       0
1  -0.632261   0.100458       0
2  -0.204317  -0.012610       0
3   0.213696   0.219907       0
4   1.033878   0.813623       0

In [11]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [12]:
#Upsampling the minority class

df_minorty = df[df['target']==1]
df_majority = df[df['target']==0]

In [34]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\itssa\OneDrive\Desktop\udemy\Python\venv\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\itssa\OneDrive\Desktop\udemy\Python\venv\Lib\site-packages (from scikit-learn) (2.5.0)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\itssa\OneDrive\Desktop\udemy\Python\venv\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\itssa\OneDrive\Desktop\udemy\Python\venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\itssa\OneDrive\Desktop\udemy\Python\venv\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\itssa\OneDrive\Desktop\udemy\Python\venv\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sklearn.utils import resample
df_minorty_upsampled = resample(df_minorty, replace=True, n_samples=len(df_majority), random_state=23)

In [17]:
df_minorty_upsampled.shape

(900, 3)

In [24]:
df_minorty_upsampled.head()

     feature_1  feature_2  target
983   1.156201   1.753080       1
940   5.050755   2.467175       1
973   3.524133   2.738930       1
954   1.591090   1.745073       1
931   2.047011   1.313393       1

In [32]:
df_upsampled = pd.concat([df_majority, df_minorty_upsampled])

In [33]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [40]:
# down sampling

import pandas as pd
import numpy as np

np.random.seed(34)
n_sample = 2000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample -n_class_0

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2':np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [39]:
# downsampling

df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [42]:
from sklearn.utils import resample
df_majority_downsampled =resample(df_majority,replace=False,
         n_samples= len(df_minority),
         random_state=23
         )

In [43]:
df_majority_downsampled.shape

(100, 3)

In [44]:
df_downsapled = pd.concat([df_majority_downsampled,df_minority])

In [45]:
df_downsapled.target.value_counts()

target
0    100
1    100
Name: count, dtype: int64